
 language: node_js
   node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
  before_script:
  - echo "no tests"
  
    docker build -t udagram-api-feed . ./udagram-api-feed 
  - docker tag udagram-api-feed salmasalma1998/udagram-api-feed :v0 
  
    docker build -t udagram-api-user . ./udagram-api-user 
  - docker tag udagram-api-user salmasalma1998/udagram-api-user:v0 
  
    docker build -t udagram-frontend . ./udagram-frontend 
  - docker tag udagram-frontend salmasalma1998 / udagram-frontend:v0 
  
  - docker build -t reverseproxy . ./udagram-reverseproxy 
  - docker tag reverseproxy . salmasalma1998/ reverseproxy:v0 
  
  after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
  - docker push salmasalma1998/udagram-api-feed :v0 
  docker push salmasalma1998/udagram-api-user :v0 
  docker push salmasalma1998/udagram-frontend :v0 
  docker push salmasalma1998/reverseproxy :v0 
